export default function MethodologyPage() {
  return (
    <main className="min-h-screen bg-slate-50">
      <div className="max-w-3xl mx-auto px-4 py-10">
        <a
          href="/"
          className="text-sm text-blue-600 hover:text-blue-800 mb-6 inline-block"
        >
          ← Back to predictions
        </a>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">How it works</h1>
        <p className="text-slate-500 mb-10 text-sm">
          An honest explanation of what this model does and what it can&apos;t do.
        </p>

        <section className="prose prose-slate max-w-none space-y-10">

          {/* Model */}
          <div>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">The prediction model</h2>
            <p className="text-slate-600 leading-relaxed">
              Predictions are generated by a weighted ensemble of three models:
            </p>
            <ul className="mt-3 space-y-2 text-slate-600">
              <li>
                <strong>Poisson regression (25%)</strong> — A Dixon-Coles model that estimates each
                team&apos;s attack and defence strength, then generates a full scoreline probability
                matrix. It&apos;s especially reliable when match data is limited and provides
                a principled statistical baseline.
              </li>
              <li>
                <strong>XGBoost (45%)</strong> — A gradient-boosted tree classifier trained on
                the full feature set. It learns complex non-linear interactions (e.g. &quot;this team
                does better against high-pressing sides when rested&quot;).
              </li>
              <li>
                <strong>LightGBM (20%)</strong> — A faster gradient boosting implementation with
                different regularisation characteristics. Provides diversity to the ensemble.
              </li>
            </ul>
            <p className="mt-3 text-slate-600 leading-relaxed">
              Each model&apos;s outputs are calibrated with isotonic regression (non-parametric,
              so it doesn&apos;t assume a particular curve shape) to make the probabilities
              match observed frequencies. The ensemble weights are fixed but can be adjusted
              in <code className="text-xs bg-slate-100 px-1 py-0.5 rounded">model_config.yaml</code>.
            </p>
          </div>

          {/* Features */}
          <div>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">Features used</h2>
            <p className="text-slate-600 mb-3 leading-relaxed">
              All rolling features use a shift-before-rolling technique to prevent data leakage
              — the model never sees the outcome of the match it&apos;s predicting.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {[
                { name: "Form (3/5/10 games)", desc: "Win rate, PPG, goals for/against, clean sheets" },
                { name: "Elo ratings", desc: "Running Elo with K=32, implies home win probability" },
                { name: "Head-to-head", desc: "5-year H2H win rates and average goals" },
                { name: "xG (Expected Goals)", desc: "Rolling xG for/against, PPDA (pressing intensity)" },
                { name: "Squad value", desc: "Transfermarkt market values, average age, injury count" },
                { name: "Tactics", desc: "Formation matchup history, player archetype advantages" },
                { name: "Context", desc: "Rest days, fixture congestion, season stage, league position" },
                { name: "Referee", desc: "Label-encoded referee ID" },
              ].map((f) => (
                <div key={f.name} className="bg-white rounded-lg border border-slate-200 p-3">
                  <p className="font-medium text-slate-800 text-sm">{f.name}</p>
                  <p className="text-slate-500 text-xs mt-0.5">{f.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Value bets */}
          <div>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">Value bet calculation</h2>
            <p className="text-slate-600 leading-relaxed">
              Bookmaker odds imply a probability (1 / decimal odds), but these raw probabilities
              sum to more than 100% because bookmakers build in a margin (the &quot;vig&quot;).
              We normalise the implied probabilities to remove the vig, then compute:
            </p>
            <div className="bg-slate-100 rounded-lg p-4 my-3 font-mono text-sm text-slate-700">
              <p>edge = model_probability − implied_probability</p>
              <p className="mt-2">kelly = (edge × decimal_odds) / (decimal_odds − 1)</p>
            </div>
            <p className="text-slate-600 leading-relaxed">
              A bet is flagged as a value bet when <strong>edge &gt; 5%</strong>. The Kelly fraction
              is the theoretically optimal bet size to maximise long-run log-wealth growth.
              In practice, most bettors use 25–50% of the full Kelly to reduce variance.
            </p>
          </div>

          {/* Disclaimer */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-5">
            <h2 className="text-base font-semibold text-amber-900 mb-2">Disclaimer</h2>
            <p className="text-amber-800 text-sm leading-relaxed">
              This is a research and educational project. No prediction system beats the market
              consistently over the long term. Past model performance does not guarantee future
              results. This is <strong>not financial or betting advice</strong>. Always gamble
              responsibly and within your means.
            </p>
          </div>

        </section>
      </div>
    </main>
  );
}
